name: peervendors
description: A P2P ecommerce market place.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 16.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0
  lottie: ^1.0.1
  dots_indicator: ^1.2.0
  curved_navigation_bar: ^0.3.4
  # carousel_pro: ^1.0.0
  carousel_slider: ^4.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  audioplayers: ^0.20.1
  #audiotagger: ^2.2.1
  animations: ^2.0.2
  animated_text_kit: ^4.2.1
  badges: ^2.0.2
  cupertino_icons: ^1.0.2 
  dio: ^4.0.1 
  email_validator: ^2.0.1
  google_sign_in: ^5.1.1
  file_picker: ^4.2.4
  firebase_app_check: ^0.0.1+3
  firebase_auth: ^1.4.1
  firebase_core: '1.7.0'# ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  firebase_messaging: '10.0.8' #^10.0.7
  #flutter_image_compress: ^1.1.0
  font_awesome_flutter: ^9.2.0
  flutter_lints: ^1.0.4
  flutter_local_notifications: ^6.0.0
  flutter_facebook_auth: ^3.5.2
  #flutter_email_sender: ^5.0.2
  flutter_staggered_grid_view: ^0.4.0
  just_audio: ^0.9.15
  flutter_launcher_icons: ^0.9.2

  twitter_login: ^4.0.1
  flutter_svg: ^0.22.0
  geolocator: ^7.0.3
  geocoding: ^2.0.1
  http: ^0.13.3
  location: ^4.3.0
  package_info: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^6.1.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  record: ^3.0.0
  rename: ^2.0.1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  smooth_star_rating: ^1.1.1
  uuid: ^3.0.4
  url_launcher: ^6.0.12
  video_player: ^2.2.0
  whatsapp_unilink: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

dependency_overrides:

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/launcher_icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  fonts:
     - family: helvetica
       fonts:
          - asset: assets/fonts/HelveticaNeue.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/flags/
     - assets/files/
     - assets/images/
     - assets/categories/
     - assets/subcategories/
